RedHatQE/teflo

- teflo/utils/config.py
Update teflo config code to not make defaults section in teflo.cfg  manadatory
> CCITCARBON_233

- teflo/provisioners/asset_provisioner.py
- tests/functional/test_asset_provisioner.py
* Updated asset_provisioner.py to log out asset id for each asset created/deleted
> CCITCARBON-235 For Openstack, display instance IDs

- CONTRIBUTE.rst
- docs/docs_confluence/changes.rst
- docs/docs_confluence/contents.rst.inc
- docs/users/definitions/provision.rst
- docs/users/definitions/report.rst
- examples/docs-usage/provision.yml
- examples/docs-usage/template.yml
* Updated provision docs to remove provider key and update examples
* Updated contribution page to change plugin template info
* Updated changelog page on confluence
> Documentation changes

- setup.py
Changed the ansible-base version to not be 2.10.6 to avoid regression bugs in this ansible version
> Modified setup.py to change ansible-base version

- docs/developers/architecture.rst
- docs/docs_confluence/report.rst
- docs/glossary.rst
- docs/users/data_pass_through.rst
- docs/users/definitions/credentials.rst
- docs/users/definitions/execute.rst
- docs/users/definitions/orchestrate.rst
- docs/users/definitions/provision.rst
- examples/docs-usage/execute.yml
- examples/docs-usage/orchestrate.yml
- examples/docs-usage/provision.yml
- examples/docs-usage/resource_labels.yml
- teflo/core.py
- teflo/files/schema.yml
- teflo/helpers.py
- teflo/resources/assets.py
- teflo/teflo.py
- tests/assets/missing_colon_sdf.yml
- tests/assets/wrong_space_sdf.yml
- tests/functional/fixtures.py
- tests/functional/test_core_classes.py
- tests/functional/test_pipeline_class.py
- tests/functional/test_resources.py
* Modified assets.py to remove role attribute
* Modified teflo.py, core.py to remove role
* Modified unit tests to remove role
* Added check in schema to throw error if role is used in provisioner params
> CCITCARBON-248 Updated code to remove role attribute from assets

- teflo/core.py
- teflo/teflo.py
- tests/localhost_scenario/scenario_local.yml
- tests/localhost_scenario/teflo.cfg
* corrected the logic
* added a provision task in the local scenario test
> CCITCARBON-262 Can't generate an inventory file for a static host without groups assigned

- docs/users/configuration.rst
- teflo/helpers.py
- teflo/utils/config.py
- tests/assets/teflo.cfg
- tests/functional/test_config_class.py
* rectified task_concurrency method in helpers.py
* Added unit test to cover this change
* Added doc change in configuration.rst
> CCITCARBON-145 Allow jinja templating within teflo.cfg

- teflo/orchestrators/ext/ansible_orchestrator_plugin/ansible_orchestrator_plugin.py
- teflo/orchestrators/ext/ansible_orchestrator_plugin/files/extensions.py
- teflo/orchestrators/ext/ansible_orchestrator_plugin/files/schema.yml
- tests/localhost_scenario/scenario_local.yml
* Removed support for using name field under orchestrate block as script/playbook path
* Removed support for using ansible_script as a boolean
* Corrected schema and extension methods for ansible orchestrator plugin
* Corrected the local scenario for cleanup task
> CCITCARBON-247 Remove backward compatibility code in the ansible_orchestrator_plugin

- setup.py
- teflo/helpers.py
> Revert "CCITCARBON-275 Use pyssh over paramiko library"

- teflo/helpers.py
- teflo/orchestrators/ext/ansible_orchestrator_plugin/ansible_orchestrator_plugin.py
> Fix the ansible stderr issue

- docs/users/variable_data.rst
- teflo/cli.py
- teflo/helpers.py
- tests/assets/teflo.cfg
- tests/assets/test_var_file.yml
- tests/functional/test_cli.py
- tests/functional/test_helpers.py
* Added method in helpers.py to look for variable_file declaration
* Added unit tests to test this method
* Added documentation to support it
> CCITCARBON 264 Default variable file precedence location and usage

- teflo/provisioners/ext/bkr_client_plugin/beaker_client_plugin.py
This change accomodates use cases where provisioning machines in beaker may not have a **/root/.ssh** directory when OS installation completes. Resulting in the provisioner failing to deploy the ssh public key. With this update, the beaker provisioner will create the ssh directory if it does not exist and then proceeds to deploy the key.
_Verification_
```
2021-06-16 07:39:37,434 WARNING Scenario workspace was not set, therefore the workspace is automatically assigned to the current working directory. You may experience problems if files needed by teflo do not exists in the scenario workspace.
2021-06-16 07:39:37,479 INFO 
2021-06-16 07:39:37,479 INFO                                TEFLO RUN (START)                               
2021-06-16 07:39:37,479 INFO …
```
> Create root users ssh directory for beaker provisioner when non existing

- docs/users/variable_data.rst
- teflo/helpers.py
- tests/assets/test_nested_var_file.yml
- tests/functional/test_cli.py
- Fix parsing problem when there is nested var use in variable files
- Added documentation and examples
- Added test
> CCITCARBON-272 Added nested variable support for -vars-data

- docs/users/definitions/orchestrate.rst
- teflo/ansible_helpers.py
- tests/localhost_scenario/ansible/variable_test_playbook.yml
- tests/localhost_scenario/scenario_local.yml
- tests/localhost_scenario/variable_1.yml
* Modified ansible_helpers.py
* Added a test in local scenario to cover this feature update
* Added docs
closes #73
> CCITCARBON-318 Ability to pass multiple files to the extra_vars module

- docs/users/install.rst
1. Fixed the install part for teflo
2. Added webhook plugin documentaion in install.rst
3. Added terraform plugin documentation in install.rst
> Fixed the documentation and added terraform to install.rst

- CHANGES.rst
Updated the Change Doc for release 1.2.1
> Updated Change Doc

- .bumpversion.cfg
- docs/conf.py
- setup.cfg
- teflo/__init__.py
Hot fix release, will include the changes in next release
> Bump version: 1.2.1 → 1.2.2

- teflo/helpers.py
- teflo/utils/resource_checker.py
- tests/functional/test_resource_checker_class.py
> Statuspage

- teflo/cli.py
- teflo/helpers.py
- tests/assets/show_test_var.yml
- tests/assets/show_vars_data.yml
- tests/functional/test_cli.py
Added --vars-data option for show command
> CCITCARBON-291 Fix the show command --vars-data

- teflo/helpers.py
- tests/assets/multiple_template.yml
- tests/assets/test_nested_var_file.yml
- tests/functional/test_cli.py
> CCITCARBON-349 Using variable files with variables as list/dict causes an exception

- CHANGES.rst
- docs/docs_confluence/compat_matrix.rst
- docs/docs_confluence/report.rst
- docs/users/install.rst
- examples/docs-usage/report.yml
* Updated confluence docs
* Updated compat matrix
* Upated change log
> Modified docs for release 1.2.3

- teflo/resources/assets.py
- tests/functional/test_resources.py
> CCITCARBON-307 invalid inventory generated when groups contains the machine name

- teflo/helpers.py
- tests/assets/multiple_template.yml
- tests/assets/test_nested_var_file.yml
- tests/functional/test_cli.py
This pr fixes #133 
The var file should be able to contain any kind of variable now
> fixed the ansible nested var issue

- teflo/helpers.py
- tests/assets/multiple_template.yml
- tests/assets/test_nested_var_file.yml
1. Fixed the ansible nested var issues
2. Added one more test data
> Fixed the nested var issues

- docs/users/definitions/include.rst
- examples/docs-usage/include.yml
- teflo/constants.py
- teflo/helpers.py
- tests/assets/teflo.cfg
- tests/assets/test_template_render.yml
- tests/functional/test_helpers.py
1. Added toggle_jinja_include parameter under defaults section in
teflo.cfg to enable the ability for teflo to handle the jinja templating in include section
2. Added unit tests
3. Added Documentation and example
> Fix issues of jinja templating in include

- .bumpversion.cfg
- CHANGES.rst
- docs/conf.py
- docs/docs_confluence/compat_matrix.rst
- docs/users/install.rst
- setup.cfg
- teflo/__init__.py
> Release1.2.5

- .bumpversion.cfg
- CHANGES.rst
- docs/conf.py
- setup.cfg
- teflo/__init__.py
> Release2.1.0

- .github/workflows/run_unit_tests.yml
- .gitignore
- docs/users/definitions/include.rst
- examples/docs-usage/include.yml
- examples/docs-usage/teflo_example.cfg
- teflo/constants.py
- teflo/helpers.py
- teflo/orchestrators/ext/ansible_orchestrator_plugin/ansible_orchestrator_plugin.py
- teflo/resources/scenario.py
- teflo/teflo.py
- tests/assets/remote_include.yml
- tests/functional/test_cli.py
- tests/localhost_scenario/sdf_library1.yml
- tests/localhost_scenario/sdf_library2.yml
- tests/localhost_scenario/sdf_library3.yml
- tests/localhost_scenario/sdf_library4.yml
- tox.ini
1. Finished the implementation for remote inclusion(first version)
2. Documentation
3. Added unit tests
(**1.More automation tests to be added**
**2.git credential function to be added**
**3.allow set download dir**
)
> remote inclusion

- docs/users/definitions/include.rst
- examples/docs-usage/include.yml
- teflo/helpers.py
1. Fixed small error when loading workspace from results.yml(when
there's no remote workspace included in include section, the
workspace will no longer change)
2. Updated the include.yml and include.rst for documentation
> Fixed error for remote inclusion

- docs/users/variable_data.rst
- teflo/ansible_helpers.py
- teflo/cli.py
- teflo/constants.py
- teflo/helpers.py
- tests/assets/scenario_graph_basic_test/sdf.yml
- tests/assets/vars_files/vardata.yml
- tests/assets/vars_files/vardatatwo.yml
- tests/functional/test_cli.py
-Changes for ANSIBLE_EXTRA_VARS_FILES option for orchestrate/execute task.  -Added option to use Multiple var_file by Dir path
> CCITCARBON-377 Changes for ANSIBLE_EXTRA_VARS_FILES

- teflo/helpers.py
- tests/assets/test_nested_var_file.yml
> Fix nested var

- teflo/core.py
- tests/functional/test_resources.py
> fixed resource name issue

- teflo/executors/ext/ansible_executor_plugin/ansible_executor_plugin.py
> CCITCARBON-433 fix for DISPLAY_SKIPPED_HOSTS option is deprecated

- docs/users/definitions/include.rst
- examples/docs-usage/include.yml
- examples/docs-usage/teflo_example.cfg
- teflo/helpers.py
- tests/localhost_scenario/sdf_remotes1.yml
- tests/localhost_scenario/sdf_remotes2.yml
- tests/localhost_scenario/sdf_remotes3.yml
- tests/localhost_scenario/sdf_remotes4.yml
added use of GIT_SSH_COMMAND env_var
> CCITCARBON-385 support of git ssh to clone remotes 

- teflo/provisioners/ext/bkr_client_plugin/beaker_client_plugin.py
> CCITCARBON-454 beaker provisioner: append to authorized_keys rather than overwrite it

- teflo/helpers.py
- teflo/teflo.py
- teflo/utils/pipeline.py
- tests/functional/test_pipeline_class.py
Right now, the on_start trigger works only on the first task in the scenario.
> CCITCARBON-379 Notifications with on_start triggers do not work correctly

- teflo/ansible_helpers.py
> CCITCARBON-477 fix to allow roles to be installed correctly from req files with only a list

- setup.py
fixed by the latest ssh-python, I updated the ssh_python verision for teflo, should work now
> modified ssh-python
